image: docker:latest

definitions:
  services:
    docker:
      memory: 2048
      privileged: true
      vars:
        DOCKER_OPTS: "--insecure-registry=harbor2.dev.huekcapital.com"

pipelines:
  branches:
    main:
    - step:
        name: "Build and Push Docker Image"
        runs-on:
        - self.hosted
        - linux
        services:
        - docker
        script:
        - export IMAGE_NAME="harbor2.dev.huekcapital.com/inspius/schedule-daily"
        - export TAG=$(git rev-parse --short HEAD)
        - echo $TAG
        - export LATEST_IMAGE="$IMAGE_NAME:latest"

        # Đăng nhập vào Docker Registry
        - echo "$DOCKER_PASSWORD" | docker login harbor2.dev.huekcapital.com -u "$DOCKER_USERNAME" --password-stdin

        - if docker manifest inspect $LATEST_IMAGE >/dev/null 2>&1; then docker pull $LATEST_IMAGE; else echo "No latest image found, skipping cache"; fi

        # Build Image
        #- docker buildx build --platform linux/amd64 -t $IMAGE_NAME:$TAG .
        - DOCKER_BUILDKIT=0 docker build --cache-from=$LATEST_IMAGE -t $IMAGE_NAME:$TAG .

        - docker tag $IMAGE_NAME:$TAG $LATEST_IMAGE
        # Push Image
        - docker push $IMAGE_NAME:$TAG
        - docker push $LATEST_IMAGE
        - echo $IMAGE_NAME:$TAG

        # Đăng xuất khỏi registry
        - docker logout harbor2.dev.huekcapital.com

        - git clone https://toannv2:$BITBUCKET_APP_PASSWORD@bitbucket.org/inspius-projects/arbitrage-manifests.git
        - cd arbitrage-manifests/_helm_templates/schedule-daily

        # Cập nhật giá trị tag trong values.yaml
        - sed -i -E 's|(^\s*tag:\s*).*|\1"'"$TAG"'"|' values.yaml

        # Commit và push thay đổi
        - git config --global user.email "ci@bitbucket.org"
        - git config --global user.name "Bitbucket CI"
        - git add values.yaml
        - git commit -m "Update schedule-daily image tag to $TAG"
        - git push origin main
