version: '3.8'

services:
  dnt_scanner_api:
    build: .
    container_name: dnt_scanner_api
    image: dnt_scanner
    environment:
      - NODE_ENV=production
    command: npm start api --watch
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  dnt_scanner_internal:
    build: .
    container_name: dnt_scanner_internal
    image: dnt_scanner
    environment:
      - NODE_ENV=production
    command: npm start internal --watch
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  dnt_scanner_scheduler:
    build: .
    container_name: dnt_scanner_scheduler
    image: dnt_scanner
    environment:
      - NODE_ENV=production
    command: npm start internal --watch
    volumes:
      - .:/app
      - /app/node_modules
    restart: always


